name: "Nightly E2E run"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:

  cleanup-runs:
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v3.0.8
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: newbuild
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/cache@v3.0.8
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: "env.GIT_DIFF != ''"
      - name: test nondeterminism
        run: |
          make test-sim-nondeterminism
        if: "env.GIT_DIFF != ''"

  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Build Docker Image
        run: make docker-build-debug
      - name: Test E2E
        run: make test-e2e

  liveness-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Install Gaia
        run: |
          make build
        if: env.GIT_DIFF
      - name: Start Local Network
        run: |
          make start-localnet-ci > liveness.out 2>&1 &
        if: env.GIT_DIFF
      - name: Test Local Network Liveness
        run: |
          ./contrib/scripts/test_localnet_liveness.sh 100 5 50 localhost
        if: env.GIT_DIFF
