name: "Nightly E2E run"
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  matrix-tests:
    uses: cosmos/gaia/.github/workflows/test.yml@main
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]       # We can add custom runners - https://github.com/actions/runner

